# Tensores PyTorch

## Vetores unidimensionais

In [1]:
import torch

In [2]:
t = torch.tensor(2)
print(t)

tensor(2)


In [3]:
a=torch.tensor([i for i in range(10)])
print(a)
print(a.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])


In [4]:
a=torch.tensor([i*i for i in range(10)])
print(a)

tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])


In [5]:
print(a[9])
print(a[9].item())

tensor(81)
81


In [6]:
print(a.type())
m=10
print(type(a))

torch.LongTensor
<class 'torch.Tensor'>


In [7]:
print(a.dim())

1


# Matriciais

In [8]:
b = torch.randn((3,3))
print(b)

tensor([[ 0.9256, -1.0160, -0.0553],
        [ 0.0655, -2.3871,  0.8301],
        [ 0.0776,  0.7411,  0.8944]])


In [9]:
print(b.shape, b.type(), b.dim())

torch.Size([3, 3]) torch.FloatTensor 2


In [ ]:
# Multiplicação de escalares

In [10]:
c = torch.ones((3,3))
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [11]:
print(3 * c)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


In [ ]:
# Soma de escalares

In [12]:
print(10 + c)

tensor([[11., 11., 11.],
        [11., 11., 11.],
        [11., 11., 11.]])


In [ ]:
# Produto entre tensores

In [13]:
t = torch.tensor([i for i in range(5)])
v = torch.tensor([3 for i in range(5)])
print(t)
print(v)

tensor([0, 1, 2, 3, 4])
tensor([3, 3, 3, 3, 3])


In [14]:
z = t * v
print(z)

tensor([ 0,  3,  6,  9, 12])


In [ ]:
# Slicing(fatiamento)

In [15]:
print(z[2:4])

tensor([6, 9])


# Diferenciação

\begin{align*}y = 2x^3 + 4x^2 + x + 2 \end{align*}

\begin{align*} \frac{dy}{dx} = 6x^2 + 8x + 1 \end{align*}

In [16]:
def func(x):
    return (2*x**3 + 4*x**2 + x + 2)

In [17]:
# Damos um valor para x
x = torch.tensor(2.0, requires_grad=True)

In [18]:
# Atribuimos a funcao á y:
y = func(x)

In [19]:
# Vemos o valor calculado:
print(y)

tensor(36., grad_fn=<AddBackward0>)


In [20]:
# Agora vamos calcular a derivada de y no ponto x=2
y.backward()

In [21]:
# Qual o valor desta derivada ?
print(x.grad)

tensor(41.)
